apiVersion: v1
kind: Namespace
metadata:
  name: webapp
---
apiVersion: v1
kind: Service
metadata:
  name: company-news
  namespace: webapp
  labels:
    app: company-news
    group: webapp
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: company-news
    group: webapp
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: company-news
  namespace: webapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: company-news
        group: webapp
    spec:
      containers:
      - name: company-news
        image: sivaprakash123/thoughtworks:appv3.0
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 90
          timeoutSeconds: 3
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 3
          periodSeconds: 60
          successThreshold: 1
          failureThreshold: 5
        env:
        - name: JAVA_OPTS
          value: '-Xmx128m -Xms128m'
        - name: SERVER_PORT
          value: "8080"
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "512Mi"
